export const ROOM_ID_LENGTH = 5;

const BASE62_32BIT_MIN_LENGTH = 30; // actually 32
const BASE62_32BIT_MAX_LENGTH = 45; // actually 43

export const ROOM_NAME_MAX_LENGTH = 50;
export const ROOM_SIGN_KEY_MIN_LENGTH = BASE62_32BIT_MIN_LENGTH;
export const ROOM_SIGN_KEY_MAX_LENGTH = BASE62_32BIT_MAX_LENGTH;
export const ROOM_ADMIN_KEY_MIN_LENGTH = BASE62_32BIT_MIN_LENGTH;
export const ROOM_ADMIN_KEY_MAX_LENGTH = BASE62_32BIT_MAX_LENGTH;
