export const ROOM_ID_LENGTH = 5;
export const ROOM_MSG_KEY_BYTES = 8;

const BASE62_8BYTES_MIN_LENGTH = 8;
const BASE62_8BYTES_MAX_LENGTH = 11;
//const BASE62_16BYTE_MIN_LENGTH = 16;
//const BASE62_16BYTE_MAX_LENGTH = 22;
const BASE62_32BYTES_MIN_LENGTH = 32;
const BASE62_32BYTES_MAX_LENGTH = 43;
const BASE62_64BYTES_MIN_LENGTH = 64;
const BASE62_64BYTES_MAX_LENGTH = 86;

export const ROOM_NAME_MAX_LENGTH = 50;
export const ROOM_SIGN_KEY_MIN_LENGTH = BASE62_32BYTES_MIN_LENGTH;
export const ROOM_SIGN_KEY_MAX_LENGTH = BASE62_32BYTES_MAX_LENGTH;
export const ROOM_ADMIN_KEY_MIN_LENGTH = BASE62_32BYTES_MIN_LENGTH;
export const ROOM_ADMIN_KEY_MAX_LENGTH = BASE62_32BYTES_MAX_LENGTH;

export const ROOM_FP_MIN_LENGTH = BASE62_32BYTES_MIN_LENGTH;
export const ROOM_FP_MAX_LENGTH = BASE62_32BYTES_MAX_LENGTH;
export const ROOM_MSG_KEY_MIN_LENGTH = BASE62_8BYTES_MIN_LENGTH;
export const ROOM_MSG_KEY_MAX_LENGTH = BASE62_8BYTES_MAX_LENGTH;
export const AUTHOR_MAX_LENGTH = 20;
export const BODY_TEXT_MAX_LENGTH = 1000;
export const BODY_MAX_LENGTH = 2000;
export const ROOM_SIGN_MIN_LENGTH = BASE62_64BYTES_MIN_LENGTH;
export const ROOM_SIGN_MAX_LENGTH = BASE62_64BYTES_MAX_LENGTH;

export const INVITE_CODE_BYTES = 16;
export const INVITE_CODE_MAX_LENGTH = 150;

export const ROOM_MSG_FP_DISP_LENGTH = 5;
