name: build-firebase

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/build-setup
        with:
          SECRET_VALUES: ${{ secrets.SECRET_VALUES }}
        id: build_setup

      - run: npm run - firebase.deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
